config/routes.rb
ApSys::Application.routes.draw do
  resources :countries
  resources :provinces
  resources :products
  resources :refenciacontables
  resource :dashboard, :only => :show

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  root :to => 'dashboards#show'

  resources :address_types
  resources :assistance_types
  resources :attention_modes
  resources :care_types
  resources :care_type_details
  resources :currencies
  resources :document_types
  resources :email_types
  resources :health_insurances do
    resources :health_insurance_plans
  end
  resources :marital_statuses
  resources :patients do
    resources :patient_health_insurances
  end
  resources :people do
    resources :person_addresses
    resources :person_emails
    resources :person_phones
  end
  resources :professionals do
    resources :professional_schedulers
    resources :professional_specialities
    resources :professional_attention_modes
    resources :professional_validations
  end
  resources :phone_types
  resources :services do
    resources :service_specialties
  end
  resources :specialties
  resources :specialty_nomenclatures
  resources :states

  resources :menus do
    resources :menu_roles
    resources :menu_users
  end
  resources :user_authorizations
  resources :user_roles

end

app/models/specialty_nomenclature.rb
class SpecialtyNomenclature < ActiveRecord::Base
	belongs_to :specialties
	belongs_to :services

	validates_presence_of		:name, :case_sensitive => false, :message => "es un dato requerido."
	validates_presence_of		:ambulatory_or_internship, :case_sensitive => false, :message => "es un dato requerido."
end

app/controllers/specialty_nomenclatures_controller.rb
class SpecialtyNomenclaturesController < ApplicationController
	respond_to :html, :xml, :json

	def index
		@specialty_nomenclatures = SpecialtyNomenclature.all
		flash.now[:notice] = "No se encontraron registros" if @specialty_nomenclatures.empty?
		respond_with(@specialty_nomenclatures)
	end

	def show
		@specialty_nomenclature = SpecialtyNomenclature.find(params[:id])
		respond_with(@specialty_nomenclature)
	end

	def new
		@specialty_nomenclature = SpecialtyNomenclature.new
		respond_with(@specialty_nomenclature)
	end

	def create
		@specialty_nomenclature = SpecialtyNomenclature.new(params[:specialty_nomenclature])
		flash[:notice] = "Especialidad por Nomenclador creada con exito." if @specialty_nomenclature.save
		respond_with(@specialty_nomenclature)
	end

	def edit
		@specialty_nomenclature = SpecialtyNomenclature.find(params[:id])
		respond_with(@specialty_nomenclature)
	end

	def update
		@specialty_nomenclature = SpecialtyNomenclature.find(params[:id])
		flash[:notice] = "Especialidad por Nomenclador actualizada con exito." if @specialty_nomenclature.update_attributes(params[:specialty_nomenclature])
		respond_with(@specialty_nomenclature)
	end

	def destroy
		@specialty_nomenclature = SpecialtyNomenclature.find(params[:id])
		@specialty_nomenclature.destroy
		flash[:notice] = "Especialidad por Nomenclador borrada con exito." if @specialty_nomenclature.destroy
		respond_with(@specialty_nomenclature)
	end
end

app/helpers/specialty_nomenclatures_helper.rb
module SpecialtyNomenclaturesHelper
end

app/views/specialty_nomenclatures/_form.html.erb
<%= form_for @specialty_nomenclature do |f| %>
	<% if @specialty_nomenclature.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@specialty_nomenclature.errors.count, "error") %> prohibido guardar Especialidad por Nomenclador:</h2>
			<ul>
			<% @specialty_nomenclature.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<table class="data" style="width:100%" >
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :specialty_id %></strong></td>
			<td style="width:70%">
				<%= f.collection_select :specialty_id, Specialty.all, :id, :name, :include_blank => 'Sin datos' %>
			</td>
		</tr>
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :name %></strong></td>
			<td style="width:70%">
				<%= f.text_field :name %>
			</td>
		</tr>
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :service_id %></strong></td>
			<td style="width:70%">
				<%= f.collection_select :service_id, Service.all, :id, :name, :include_blank => 'Sin datos' %>
			</td>
		</tr>
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :nomenclature_id %></strong></td>
			<td style="width:70%">
				<%= f.text_field :nomenclature_id %>
			</td>
		</tr>
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :ambulatory_or_internship %></strong></td>
			<td style="width:70%">
				<%= f.text_field :ambulatory_or_internship %>
			</td>
		</tr>
	</table>
	<p><%= f.submit %></p>
<% end %>

app/views/specialty_nomenclatures/edit.html.erb
<h1>Editar Especialidad por Nomenclador</h1>

<%= render 'form' %>

<p>
	<%= link_to "Ver", @specialty_nomenclature %> |
	<%= link_to "Especialidades por Nomenclador", specialty_nomenclatures_path %>
</p>

app/views/specialty_nomenclatures/index.html.erb
<h1>Especialidades por Nomenclador</h1>

<table>
	<tr>
		<th>Specialty</th>
		<th>Name</th>
		<th>Service</th>
		<th>Nomenclature</th>
		<th>Ambulatory Or Internship</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% for specialty_nomenclature in @specialty_nomenclatures %>
		<tr>
			<td><%= specialty_nomenclature.specialty_id %></td>
			<td><%= specialty_nomenclature.name %></td>
			<td><%= specialty_nomenclature.service_id %></td>
			<td><%= specialty_nomenclature.nomenclature_id %></td>
			<td><%= specialty_nomenclature.ambulatory_or_internship %></td>
            <td><a href="/specialty_nomenclatures/<%= specialty_nomenclature.id.to_s %>"><img alt="Ver" src="images/icons/16x16/application_get.png" title="Ver" /></a></td>
            <td><a href="/specialty_nomenclatures/<%= specialty_nomenclature.id.to_s %>/edit"><img alt="Editar" src="images/icons/16x16/application_edit.png" title="Editar" /></a></td>
            <td><a href="/specialty_nomenclatures/<%= specialty_nomenclature.id.to_s %>" data-confirm="Esta ud. seguro?" data-method="delete" rel="nofollow">
				<img alt="Eliminar" src="images/icons/16x16/application_delete.png" title="Eliminar" /></a>
			</td>
		</tr>
	<% end %>
</table>
<p><%= link_to "Nueva Especialidad por Nomenclador", new_specialty_nomenclature_path %></p>

app/views/specialty_nomenclatures/new.html.erb
<h1>Nuevo Especialidad por Nomenclador</h1>

<%= render 'form' %>

<p><%= link_to "Especialidades por Nomenclador", specialty_nomenclatures_path %></p>

app/views/specialty_nomenclatures/show.html.erb
<h1>Especialidad por Nomenclador</h1>
<table class="data" style="width:50%">
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Specialty:</strong></td>
		<td style="width:70%"><%= @specialty_nomenclature.specialty_id %></td>
	</tr>
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Name:</strong></td>
		<td style="width:70%"><%= @specialty_nomenclature.name %></td>
	</tr>
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Service:</strong></td>
		<td style="width:70%"><%= @specialty_nomenclature.service_id %></td>
	</tr>
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Nomenclature:</strong></td>
		<td style="width:70%"><%= @specialty_nomenclature.nomenclature_id %></td>
	</tr>
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Ambulatory Or Internship:</strong></td>
		<td style="width:70%"><%= @specialty_nomenclature.ambulatory_or_internship %></td>
	</tr>
</table>
<p>
	<%= link_to "Editar", edit_specialty_nomenclature_path(@specialty_nomenclature) %> |
	<%= link_to "Eliminar", @specialty_nomenclature, :confirm => 'Esta seguro?', :method => :delete %> |
	<%= link_to "Especialidades por Nomenclador", specialty_nomenclatures_path %>
</p>