config/routes.rb
ApSys::Application.routes.draw do
  resources :countries
  resources :provinces
  resources :products
  resources :refenciacontables
  resource :dashboard, :only => :show

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  root :to => 'dashboards#show'

  resources :address_types
  resources :assistance_types
  resources :attention_modes
  resources :care_types
  resources :care_type_details
  resources :currencies
  resources :document_types
  resources :email_types
  resources :health_insurances do
    resources :health_insurance_plans
  end
  resources :marital_statuses
  resources :patients do
    resources :patient_health_insurances
  end
  resources :people do
    resources :person_addresses
    resources :person_emails
    resources :person_phones
  end
  resources :professionals do
    resources :professional_schedulers
    resources :professional_specialities
    resources :professional_attention_modes
    resources :professional_validations
  end
  resources :phone_types
  resources :services do
    resources :service_specialties
  end
  resources :specialties
  resources :specialty_nomenclatures
  resources :states

  resources :menus do
    resources :menu_roles
    resources :menu_users
  end
  resources :user_authorizations
  resources :user_roles

end

app/models/professional_speciality.rb
class ProfessionalSpeciality < ActiveRecord::Base
	belongs_to :professionals
	belongs_to :specialties

	validates_numericality_of	:professional_id, :greater_than_or_equal_to => 0 , :message => "es un dato requerido."
	validates_numericality_of	:specialty_id, :greater_than_or_equal_to => 0 , :message => "es un dato requerido."
end

app/controllers/professional_specialities_controller.rb
class ProfessionalSpecialitiesController < ApplicationController
	respond_to :html, :xml, :json

	def index
		@professional_specialities = ProfessionalSpeciality.all
		flash.now[:notice] = "No se encontraron registros" if @professional_specialities.empty?
		respond_with(@professional_specialities)
	end

	def show
		@professional_speciality = ProfessionalSpeciality.find(params[:id])
		respond_with(@professional_speciality)
	end

	def new
		@professional_speciality = ProfessionalSpeciality.new
		respond_with(@professional_speciality)
	end

	def create
		@professional_speciality = ProfessionalSpeciality.new(params[:professional_speciality])
		flash[:notice] = "Professional Speciality creada con exito." if @professional_speciality.save
		respond_with(@professional_speciality)
	end

	def edit
		@professional_speciality = ProfessionalSpeciality.find(params[:id])
		respond_with(@professional_speciality)
	end

	def update
		@professional_speciality = ProfessionalSpeciality.find(params[:id])
		flash[:notice] = "Professional Speciality actualizada con exito." if @professional_speciality.update_attributes(params[:professional_speciality])
		respond_with(@professional_speciality)
	end

	def destroy
		@professional_speciality = ProfessionalSpeciality.find(params[:id])
		@professional_speciality.destroy
		flash[:notice] = "Professional Speciality borrada con exito." if @professional_speciality.destroy
		respond_with(@professional_speciality)
	end
end

app/helpers/professional_specialities_helper.rb
module ProfessionalSpecialitiesHelper
end

app/views/professional_specialities/_form.html.erb
<%= form_for @professional_speciality do |f| %>
	<% if @professional_speciality.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@professional_speciality.errors.count, "error") %> prohibido guardar Professional Speciality:</h2>
			<ul>
			<% @professional_speciality.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<table class="data" style="width:100%" >
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :professional_id %></strong></td>
			<td style="width:70%">
				<%= f.text_field :professional_id %>
			</td>
		</tr>
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :specialty_id %></strong></td>
			<td style="width:70%">
				<%= f.collection_select :specialty_id, Specialty.all, :id, :name %>
			</td>
		</tr>
	</table>
	<p><%= f.submit %></p>
<% end %>

app/views/professional_specialities/edit.html.erb
<h1>Editar Professional Speciality</h1>

<%= render 'form' %>

<p>
	<%= link_to "Ver", @professional_speciality %> |
	<%= link_to "Professional Specialities", professional_specialities_path %>
</p>

app/views/professional_specialities/index.html.erb
<h1>Professional Specialities</h1>

<table>
	<tr>
		<th>Professional</th>
		<th>Specialty</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% for professional_speciality in @professional_specialities %>
		<tr>
			<td><%= professional_speciality.professional_id %></td>
			<td><%= professional_speciality.specialty_id %></td>
            <td><a href="/professional_specialities/<%= professional_speciality.id.to_s %>"><img alt="Ver" src="images/icons/16x16/application_get.png" title="Ver" /></a></td>
            <td><a href="/professional_specialities/<%= professional_speciality.id.to_s %>/edit"><img alt="Editar" src="images/icons/16x16/application_edit.png" title="Editar" /></a></td>
            <td><a href="/professional_specialities/<%= professional_speciality.id.to_s %>" data-confirm="Esta ud. seguro?" data-method="delete" rel="nofollow">
				<img alt="Eliminar" src="images/icons/16x16/application_delete.png" title="Eliminar" /></a>
			</td>
		</tr>
	<% end %>
</table>
<p><%= link_to "Nueva Professional Speciality", new_professional_speciality_path %></p>

app/views/professional_specialities/new.html.erb
<h1>Nuevo Professional Speciality</h1>

<%= render 'form' %>

<p><%= link_to "Professional Specialities", professional_specialities_path %></p>

app/views/professional_specialities/show.html.erb
<h1>Professional Speciality</h1>
<table class="data" style="width:50%">
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Professional:</strong></td>
		<td style="width:70%"><%= @professional_speciality.professional_id %></td>
	</tr>
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Specialty:</strong></td>
		<td style="width:70%"><%= @professional_speciality.specialty_id %></td>
	</tr>
</table>
<p>
	<%= link_to "Editar", edit_professional_speciality_path(@professional_speciality) %> |
	<%= link_to "Eliminar", @professional_speciality, :confirm => 'Esta seguro?', :method => :delete %> |
	<%= link_to "Professional Specialities", professional_specialities_path %>
</p>