config/routes.rb
ApSys::Application.routes.draw do
  resources :countries
  resources :provinces
  resources :products
  resources :refenciacontables
  resource :dashboard, :only => :show

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  root :to => 'dashboards#show'

  resources :address_types
  resources :assistance_types
  resources :attention_modes
  resources :care_types
  resources :care_type_details
  resources :currencies
  resources :document_types
  resources :email_types
  resources :health_insurances do
    resources :health_insurance_plans
  end
  resources :marital_statuses
  resources :patients do
    resources :patient_health_insurances
  end
  resources :people do
    resources :person_addresses
    resources :person_emails
    resources :person_phones
  end
  resources :professionals do
    resources :professional_schedulers
    resources :professional_specialities
    resources :professional_attention_modes
    resources :professional_validations
  end
  resources :phone_types
  resources :services do
    resources :service_specialties
  end
  resources :specialties
  resources :specialty_nomenclatures
  resources :states

  resources :menus do
    resources :menu_roles
    resources :menu_users
  end
  resources :user_authorizations
  resources :user_roles

end

app/models/currency.rb
class Currency < ActiveRecord::Base
	belongs_to :companies

	validates_presence_of		:name, :case_sensitive => false, :message => "es un dato requerido."
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
	respond_to :html, :xml, :json

	def index
		@currencies = Currency.all
		flash.now[:notice] = "No se encontraron registros" if @currencies.empty?
		respond_with(@currencies)
	end

	def show
		@currency = Currency.find(params[:id])
		respond_with(@currency)
	end

	def new
		@currency = Currency.new
		respond_with(@currency)
	end

	def create
		@currency = Currency.new(params[:currency])
		@currency.company_id = current_company.id
		flash[:notice] = "Moneda creada con exito." if @currency.save
		respond_with(@currency)
	end

	def edit
		@currency = Currency.find(params[:id])
		respond_with(@currency)
	end

	def update
		@currency = Currency.find(params[:id])
		flash[:notice] = "Moneda actualizada con exito." if @currency.update_attributes(params[:currency])
		respond_with(@currency)
	end

	def destroy
		@currency = Currency.find(params[:id])
		@currency.destroy
		flash[:notice] = "Moneda borrada con exito." if @currency.destroy
		respond_with(@currency)
	end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for @currency do |f| %>
	<% if @currency.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@currency.errors.count, "error") %> prohibido guardar Moneda:</h2>
			<ul>
			<% @currency.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<table class="data" style="width:100%" >
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :name %></strong></td>
			<td style="width:70%">
				<%= f.text_field :name %>
			</td>
		</tr>
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :code %></strong></td>
			<td style="width:70%">
				<%= f.text_field :code %>
			</td>
		</tr>
		<tr>
			<td style="width:30%;background-color: #C3D5D5;"><strong><%= f.label :default %></strong></td>
			<td style="width:70%">
				<%= f.check_box :default %>
			</td>
		</tr>
	</table>
	<p><%= f.submit %></p>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editar Moneda</h1>

<%= render 'form' %>

<p>
	<%= link_to "Ver", @currency %> |
	<%= link_to "Monedas", currencies_path %>
</p>

app/views/currencies/index.html.erb
<h1>Monedas</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Code</th>
		<th>Default</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% for currency in @currencies %>
		<tr>
			<td><%= currency.name %></td>
			<td><%= currency.code %></td>
			<td><%= check_box_tag "eula", currency.default, currency.default, :disabled => true %></td>
            <td><a href="/currencies/<%= currency.id.to_s %>"><img alt="Ver" src="images/icons/16x16/application_get.png" title="Ver" /></a></td>
            <td><a href="/currencies/<%= currency.id.to_s %>/edit"><img alt="Editar" src="images/icons/16x16/application_edit.png" title="Editar" /></a></td>
            <td><a href="/currencies/<%= currency.id.to_s %>" data-confirm="Esta ud. seguro?" data-method="delete" rel="nofollow">
				<img alt="Eliminar" src="images/icons/16x16/application_delete.png" title="Eliminar" /></a>
			</td>
		</tr>
	<% end %>
</table>
<p><%= link_to "Nueva Moneda", new_currency_path %></p>

app/views/currencies/new.html.erb
<h1>Nuevo Moneda</h1>

<%= render 'form' %>

<p><%= link_to "Monedas", currencies_path %></p>

app/views/currencies/show.html.erb
<h1>Moneda</h1>
<table class="data" style="width:50%">
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Name:</strong></td>
		<td style="width:70%"><%= @currency.name %></td>
	</tr>
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Code:</strong></td>
		<td style="width:70%"><%= @currency.code %></td>
	</tr>
	<tr>
		<td style="width:30%;background-color: #C3D5D5;"><strong>Default:</strong></td>
		<td style="width:70%"><%= @currency.default %></td>
	</tr>
</table>
<p>
	<%= link_to "Editar", edit_currency_path(@currency) %> |
	<%= link_to "Eliminar", @currency, :confirm => 'Esta seguro?', :method => :delete %> |
	<%= link_to "Monedas", currencies_path %>
</p>