config/routes.rb
ApSys::Application.routes.draw do
  resources :countries
  resources :provinces
  resources :products
  resources :refenciacontables
  resource :dashboard, :only => :show

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  root :to => 'dashboards#show'

  resources :address_types
  resources :assistance_types
  resources :attention_modes
  resources :care_types
  resources :care_type_details
  resources :currencies
  resources :document_types
  resources :email_types
  resources :health_insurances do
    resources :health_insurance_plans
  end
  resources :marital_statuses
  resources :patients do
    resources :patient_health_insurances
  end
  resources :people do
    resources :person_addresses
    resources :person_emails
    resources :person_phones
  end
  resources :professionals do
    resources :professional_schedulers
    resources :professional_specialities
    resources :professional_attention_modes
    resources :professional_validations
  end
  resources :phone_types
  resources :services do
    resources :service_specialties
  end
  resources :specialties
  resources :specialty_nomenclatures
  resources :states

  resources :menus do
    resources :menu_roles
    resources :menu_users
  end
  resources :user_authorizations
  resources :user_roles

end

app/views/shared/_change_current_company.html.haml
= raw " &raquo; #{current_company.name.titlecase}" unless current_company.blank?
= link_to(icon('application_edit', :small, :title => 'Administración de Companías'), companies_path, :style => 'float:right;')
- if current_user.companies.many?
  %div{:style => 'float:right;margin-top:11px;'}
    = collection_select(:company, :id, current_user.companies, :id, :name, { :include_blank => '-- Cambiar de Companía --'}, :onchange => 'location.href="?cc="+$(this).val();')

app/views/shared/_common_form_buttons.html.haml
= link_to_function(icon('disk') + 'Guardar', "$(this).closest('form').submit();", :class => :button)
= link_to_function(icon('arrow_rotate_clockwise') + 'Limpiar', "$(this).closest('form').reset();", :class => :button)
.clear

app/views/shared/_main_navigation.html.haml
= navigation(:id => "main-navigation") do |menu|
  - if current_user.can_operated_engine?(:odiseo) 
    - menu.item(Entry.model_name.human.pluralize, entries_path, :active => controller.controller_name.include?('entries'))
    - menu.item(Exercise.model_name.human.pluralize, exercises_path, :active => controller.controller_name.include?('exercises'))
  - if current_user.can_operated_engine?(:ares) 
    - menu.item(Cliente.model_name.human.pluralize, clientes_path, :active => controller.controller_name.include?('clientes'))
    - menu.item('Tasa de IVA', tasaivas_path, :active => controller.controller_name.include?('tasaivas'))
    - menu.item('Condiciones de IVA', condicionivas_path, :active => controller.controller_name.include?('condicionivas'))
    - menu.item('Referencias contables', refenciacontables_path, :active => controller.controller_name.include?('refenciacontables'))
  - if current_user.can_operated_engine?(:hefesto) 
    - menu.item(Supplier.model_name.human.pluralize, suppliers_path, :active => controller.controller_name.include?('suppliers'))
  - if current_user.can_operated_engine?(:ares) 
    - menu.item(Product.model_name.human.pluralize, products_path, :active => controller.controller_name.include?('products'))
    - menu.item(Country.model_name.human.pluralize, countries_path, :active => controller.controller_name.include?('countries'))
    - menu.item(Province.model_name.human.pluralize, provinces_path, :active => controller.controller_name.include?('provinces'))

app/views/shared/_sidebar.html.haml
.block
  %ul.navigation
    %li= link_to("News Item 3", news_path(3))

app/views/shared/_status_menu.html.haml
%h5= "Conectado como #{current_user.email}"

app/views/shared/_user_navigation.html.haml
= navigation(:id => "user-navigation") do |menu|
  - menu.item(image_tag('session/home.png'), root_path, :alt => 'Principal')
  - menu.item(image_tag('session/account.png'), edit_user_registration_path, :alt => 'Editar mis Datos')
  - menu.item(image_tag('session/logout.png'), logout_path, :alt => 'Salir')

%br
%br